'use strict';
/* First-run starter files. Pure data — no DOM, no obsidian import.

   Seeded from Ruan's real "Get Over The Bar" program (at-home strength,
   4 days/week, one hard goal — the muscle-up) rather than a generic library,
   so the plugin is useful the moment it's set up. Every file here is written
   with writeIfAbsent: a re-run never overwrites real data. */

/* Demonstration media, two open sources:
     - yuhonas/free-exercise-db (Unlicense — public domain): start/finish
       photo pairs. Only true movement matches; where the nearest match is a
       variant (parallel-bar dips, kettlebell pistol) the note body says so.
     - wger.de (CC-BY-SA 4.0): extra photos and the only open exercise
       VIDEOS around (by Goulart). Attribution lives in the note bodies and
       in NOTICE; the media streams from wger.de when online.
   URLs load when online and the detail page degrades quietly offline.
   isSeedMediaUrl() below is the refresh gate — keep it covering every host
   used here. */
const IMG = id => [0, 1].map(n => `https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/${id}/${n}.jpg`);
const WGER = p => `https://wger.de/media/${p}`;

/* True when a media URL is one the SEED wrote (vs. something the user set
   themselves) — the only values a starter-media refresh may overwrite. */
const isSeedMediaUrl = u => /^https:\/\/(raw\.githubusercontent\.com\/yuhonas\/free-exercise-db\/|wger\.de\/media\/)/.test((u || '').toString());

const SEED_EXERCISES = [
  { name: 'Pull-ups', type: 'strength', muscles: ['back', 'biceps', 'forearms'], equipment: 'bar', unit: 'reps',
    image: [...IMG('Pullups'), WGER('exercise-images/475/b0554016-16fd-4dbe-be47-a2a17d16ae0e.jpg')],
    video: WGER('exercise-video/475/83067ffe-ccb9-4e22-8507-5131b211ce74.MOV'),
    note: [
      '1. Grab the bar just outside shoulder width, palms away, arms fully extended.',
      '2. Pull the shoulder blades down first, then drive the elbows to your ribs until your chin clears the bar.',
      '3. Lower under control to a full hang every rep.',
      '',
      '**Cue:** stop 1–2 reps before failure every set — quality volume, not grinding. Half of the muscle-up.',
      '',
      'Photo 3: Imobard · video: Goulart — both via wger.de, CC-BY-SA 4.0.',
    ].join('\n') },
  { name: 'Explosive High Pull-ups', type: 'strength', muscles: ['back', 'biceps'], equipment: 'bar', unit: 'reps',
    note: [
      '1. Set up like a normal pull-up, but pull as FAST as you can.',
      '2. Aim chest — then belly — toward the bar; let the elbows drive down and back.',
      '3. Reset fully between reps; speed is the point, not reps.',
      '',
      '**Cue:** trains the "pop" that carries you over the bar in a muscle-up.',
    ].join('\n') },
  { name: 'Inverted Rows', type: 'strength', muscles: ['back', 'shoulders'], equipment: 'bar', unit: 'reps',
    image: IMG('Inverted_Row'),
    note: [
      '1. Set a bar around hip height; hang under it, heels on the floor, body straight as a plank.',
      '2. Pull your chest to the bar, squeezing the shoulder blades together.',
      '3. Lower slowly; don\'t let the hips sag. Walk feet further forward to make it harder.',
      '',
      '**Cue:** shoulder-health insurance — keep rows in even when time is tight.',
    ].join('\n') },
  { name: 'Straight-bar Dips', type: 'strength', muscles: ['chest', 'triceps', 'shoulders'], equipment: 'bar', unit: 'reps',
    image: IMG('Parallel_Bar_Dip'),
    video: WGER('exercise-video/194/d039ec90-474d-47a9-a3ad-bf0b00828c82.MP4'),
    note: [
      '1. Support yourself on top of a single straight bar, hands just outside your hips, arms locked.',
      '2. Lean slightly forward and bend the elbows until the bar reaches your lower chest / upper abs.',
      '3. Press back to a FULL lockout at the top.',
      '',
      '**Cue:** the other half of the muscle-up — the top-out is exactly this position.',
      '',
      'Media shows PARALLEL-BAR dips — same press pattern; on a straight bar both hands sit in front of you and the lean is stronger. Video: Goulart via wger.de, CC-BY-SA 4.0.',
    ].join('\n') },
  { name: 'Push-ups', type: 'strength', muscles: ['chest', 'triceps', 'core'], equipment: 'bodyweight', unit: 'reps',
    image: IMG('Pushups'),
    note: [
      '1. Hands under the shoulders, body one straight line from head to heels.',
      '2. Lower until the chest nearly touches the floor, elbows ~45° from the body.',
      '3. Press up to full lockout without the hips sagging or piking.',
      '',
      '**Cue:** elevate hands on the box if full push-ups are tough.',
    ].join('\n') },
  { name: 'Box Jumps', type: 'strength', muscles: ['quads', 'glutes', 'calves'], equipment: 'box', unit: 'reps',
    image: IMG('Front_Box_Jump'),
    note: [
      '1. Stand a short step from the box, feet hip width.',
      '2. Dip, swing the arms, and jump; land SOFT and quiet with both feet fully on the box.',
      '3. Stand tall on top — then STEP down every rep. Never jump down.',
      '',
      '**Cue:** landings over height, always. Jumping down repeatedly is the #1 injury risk.',
    ].join('\n') },
  { name: 'Dead Hang', type: 'skill', muscles: ['forearms', 'shoulders'], equipment: 'bar', unit: 'seconds',
    note: [
      '1. Grab the bar palms away, hands shoulder width.',
      '2. Hang with arms straight; let the shoulders decompress but keep them "plugged in" (not shrugged into your ears).',
      '3. Breathe. Time the hold.',
      '',
      '**Cue:** grip + shoulder decompression — prehab gold at 40.',
    ].join('\n') },
  { name: 'Plank', type: 'skill', muscles: ['core'], equipment: 'bodyweight', unit: 'seconds',
    image: IMG('Plank'),
    note: [
      '1. Forearms on the floor, elbows under shoulders, feet together.',
      '2. Squeeze glutes and brace the abs so the body is one rigid line.',
      '3. Hold. The set ends when the hips sag or pike — not when the timer says so.',
      '',
      '**Cue:** flat back, hips don\'t sag. Sub in side planks now and then.',
    ].join('\n') },
  { name: 'Romanian Deadlift', type: 'strength', muscles: ['hamstrings', 'glutes', 'back'], equipment: 'dumbbells', unit: 'kg', motion_sensitivity: 'low',
    image: IMG('Romanian_Deadlift'),
    video: WGER('exercise-video/507/307e7276-a14d-4ea0-b579-f5b0dbc6f5af.MOV'),
    note: [
      '1. Stand tall holding dumbbells in front of the thighs, soft knees.',
      '2. Push the hips BACK, sliding the weights down the legs, chest proud, back flat.',
      '3. Feel the hamstrings load around mid-shin, then drive the hips forward to stand.',
      '',
      '**Cue:** two-leg first, progress to single-leg. The posterior-chain work your back and jumps need.',
      '',
      'Video: Goulart via wger.de, CC-BY-SA 4.0.',
    ].join('\n') },
  { name: 'Bulgarian Split Squat', type: 'strength', muscles: ['quads', 'glutes'], equipment: 'dumbbells', unit: 'kg',
    note: [
      '1. Rear foot up on the box behind you, front foot far enough forward that the knee tracks over the toes.',
      '2. Lower straight down until the front thigh is about parallel.',
      '3. Drive through the front heel to stand.',
      '',
      '**Cue:** add weight when 8 feels easy. Builds the single-leg strength that leads to the pistol.',
    ].join('\n') },
  { name: 'Pistol Squat Progression', type: 'skill', muscles: ['quads', 'glutes', 'core'], equipment: 'bodyweight', unit: 'reps',
    image: IMG('Kettlebell_Pistol_Squat'),
    note: [
      '1. Stand on one leg, the other held straight in front.',
      '2. Sit back and down as far as your current progression allows — to a box at first.',
      '3. Stand without touching the free leg down.',
      '',
      '**Progression:** sit to a box → lower surface → full pistol. Superset with split squats early on.',
      '',
      'Photos show the kettlebell version — the counterweight actually makes it EASIER; same pattern without it.',
    ].join('\n') },
  { name: 'Toes-to-bar Ladder', type: 'skill', muscles: ['core', 'forearms'], equipment: 'bar', unit: 'reps', motion_sensitivity: 'low',
    image: IMG('Hanging_Leg_Raise'),
    note: [
      '1. Hang from the bar, shoulders engaged, body still.',
      '2. Work the first rung you can\'t cheat: knee raise → straight-leg raise → toes to the bar.',
      '3. Lower SLOWLY — no swinging, no kipping.',
      '',
      '**Cue:** builds the hollow-body tension a muscle-up needs. (Image shows the leg-raise rung.)',
    ].join('\n') },
  { name: 'L-sit & Dragon Flag', type: 'skill', muscles: ['core'], equipment: 'bodyweight', unit: 'seconds',
    note: [
      '1. L-sit: hands on the floor or two dumbbells, press down and lift both straight legs to horizontal. Hold.',
      '2. Dragon flag: lie back gripping a bench behind your head; lower the whole rigid body from vertical as slowly as possible.',
      '',
      '**Cue:** add only once toes-to-bar is solid. These are earned, not rushed.',
    ].join('\n') },
  { name: 'Muscle-ups', type: 'skill', muscles: ['back', 'chest', 'triceps', 'core'], equipment: 'bar', unit: 'reps',
    image: IMG('Muscle_Up'),
    note: [
      '1. False grip helps: wrists over the bar, not knuckles.',
      '2. Pull explosively high (chest to bar and past it) while leaning back, then drive the chest OVER the bar.',
      '3. The transition: elbows from below the bar to above it in one motion — then press out to a straight-bar dip lockout.',
      '',
      '**The mission.** Unlocks as skill work at 8–10 clean pull-ups AND 8–10 clean dips: band-assisted reps + slow negatives first.',
    ].join('\n') },

  /* ---- Added 27 Aug 2026: the warm-up and prehab moves the plan already
     names, a vertical-press track, and hinge/grip/lateral-core gaps. ---- */
  { name: 'Scapular Pull-ups', type: 'skill', muscles: ['back', 'shoulders'], equipment: 'bar', unit: 'reps', motion_sensitivity: 'high',
    image: IMG('Scapular_Pull-Up'),
    note: [
      '1. Hang from the bar with completely straight arms.',
      '2. WITHOUT bending the elbows, pull your shoulder blades down and together so your chest rises an inch or two.',
      '3. Hold a beat at the top, then let the shoulders rise back to a full hang.',
      '',
      '**Cue:** already in your warm-up — this is what teaches the lats to switch on before the first real pull-up.',
    ].join('\n') },
  { name: 'Band Pull-Aparts', type: 'mobility', muscles: ['shoulders', 'back'], equipment: 'band', unit: 'reps', motion_sensitivity: 'high',
    image: IMG('Band_Pull_Apart'),
    note: [
      '1. Hold a band at shoulder width, arms straight out in front of you.',
      '2. Pull the band apart until your arms are wide, squeezing the shoulder blades together.',
      '3. Return slowly under tension — don\'t let it snap back.',
      '',
      '**Cue:** 15 every warm-up. Cheap insurance for the shoulders you press with.',
    ].join('\n') },
  { name: 'Hollow Hold', type: 'skill', muscles: ['core'], equipment: 'bodyweight', unit: 'seconds',
    note: [
      '1. Lie on your back and press the lower back FLAT into the floor.',
      '2. Lift shoulders and legs a few inches, arms overhead, so the body makes a shallow dish.',
      '3. Hold that shape and breathe.',
      '',
      '**Cue:** the flat lower back IS the exercise — if it arches, raise your legs higher. This is the body line a muscle-up needs.',
    ].join('\n') },
  { name: 'Box Step-ups', type: 'strength', muscles: ['quads', 'glutes'], equipment: 'box', unit: 'reps',
    image: IMG('Step-up_with_Knee_Raise'),
    note: [
      '1. Place one whole foot on the box.',
      '2. Drive through that heel to stand tall on top — let the trailing leg do as little as possible.',
      '3. Step back down under control and alternate.',
      '',
      '**Cue:** 10 easy ones in the warm-up prime knees and ankles before jumps.',
      '',
      'Photos show the knee-raise version — same step; add the knee drive at the top if you want it.',
    ].join('\n') },
  { name: 'Dead Bug', type: 'skill', muscles: ['core'], equipment: 'bodyweight', unit: 'reps', motion_sensitivity: 'low',
    image: IMG('Dead_Bug'),
    note: [
      '1. On your back, arms straight up, knees bent at 90 degrees over the hips.',
      '2. Slowly lower one arm overhead and the OPPOSITE leg toward the floor.',
      '3. Return and swap sides. The lower back stays pressed flat throughout.',
      '',
      '**Cue:** the core work to keep when the lower back is grumbling — all the bracing, none of the loading.',
    ].join('\n') },
  { name: 'Superman', type: 'strength', muscles: ['back', 'glutes'], equipment: 'bodyweight', unit: 'seconds',
    image: IMG('Superman'),
    note: [
      '1. Lie face down, arms extended in front.',
      '2. Lift chest, arms and legs off the floor and squeeze the glutes.',
      '3. Hold, then lower under control.',
      '',
      '**Cue:** the spinal-erector counterweight to all the hanging and pressing. Gentle and controlled — never a thrash.',
    ].join('\n') },
  { name: 'Chin-ups', type: 'strength', muscles: ['back', 'biceps'], equipment: 'bar', unit: 'reps',
    image: IMG('Chin-Up'),
    note: [
      '1. Grip the bar with palms facing YOU, about shoulder width.',
      '2. Pull until your chin clears the bar, elbows driving down.',
      '3. Lower to a full hang every rep.',
      '',
      '**Cue:** the supinated grip lets the biceps help, so you will usually get a few more than pull-ups — a good way to add pulling volume on the way to the 10-rep gateway.',
    ].join('\n') },
  { name: 'Pike Push-ups', type: 'strength', muscles: ['shoulders', 'triceps'], equipment: 'bodyweight', unit: 'reps',
    note: [
      '1. Hands and feet on the floor, hips pushed high into an upside-down V.',
      '2. Bend the elbows to lower the crown of your head toward the floor between your hands.',
      '3. Press back up to straight arms.',
      '',
      '**Cue:** the vertical press you otherwise never train. Walk your feet closer — or up onto the box — to make it harder. This is the road to handstand push-ups.',
    ].join('\n') },
  { name: 'Handstand Push-ups', type: 'skill', muscles: ['shoulders', 'triceps', 'core'], equipment: 'bodyweight', unit: 'reps',
    image: IMG('Handstand_Push-Ups'),
    note: [
      '1. Kick up to a handstand with your heels resting on a wall, hands a little wider than shoulders.',
      '2. Lower under control until your head lightly touches the floor.',
      '3. Press back to a full lockout.',
      '',
      '**Cue:** earn these with pike push-ups first. Overhead pressing strength that carries straight into the muscle-up top-out.',
    ].join('\n') },
  { name: 'Goblet Squat', type: 'strength', muscles: ['quads', 'glutes', 'core'], equipment: 'dumbbells', unit: 'kg',
    image: IMG('Goblet_Squat'),
    note: [
      '1. Hold one dumbbell or kettlebell against your chest with both hands.',
      '2. Squat down between your knees, chest tall, until the thighs pass parallel.',
      '3. Drive up through mid-foot.',
      '',
      '**Cue:** the counterweight out front makes depth easier — it doubles as an ankle and hip mobility drill while still loading the legs.',
    ].join('\n') },
  { name: 'Kettlebell Swing', type: 'strength', muscles: ['hamstrings', 'glutes', 'back'], equipment: 'kettlebell', unit: 'kg', motion_sensitivity: 'low',
    image: IMG('One-Arm_Kettlebell_Swings'),
    note: [
      '1. Hinge at the hips and hike the bell back between your legs.',
      '2. Snap the hips FORWARD to float the bell up to chest height — the arms are just rope.',
      '3. Let it swing back down, hinging again to absorb it.',
      '',
      '**Cue:** hips do the work, not the shoulders. The fastest way to train the hinge that powers your box jumps.',
      '',
      'Photos show the one-arm version — two hands is the identical hinge.',
    ].join('\n') },
  { name: 'Single-leg Glute Bridge', type: 'strength', muscles: ['glutes', 'hamstrings'], equipment: 'bodyweight', unit: 'reps', motion_sensitivity: 'low',
    image: IMG('Single_Leg_Glute_Bridge'),
    note: [
      '1. On your back, one foot planted, the other leg held straight out.',
      '2. Drive through the planted heel to lift the hips until the body is a straight line.',
      '3. Squeeze the glute at the top, lower slowly, then swap legs.',
      '',
      '**Cue:** glute strength without loading the spine — the accessory that helps keep the ITB quiet.',
    ].join('\n') },
  { name: 'Reverse Lunge', type: 'strength', muscles: ['quads', 'glutes'], equipment: 'dumbbells', unit: 'kg',
    image: IMG('Dumbbell_Lunges'),
    note: [
      '1. Stand tall, then step one foot BACK into a lunge.',
      '2. Lower until both knees are near 90 degrees, front shin vertical.',
      '3. Drive through the front heel to stand, and alternate.',
      '',
      '**Cue:** stepping back is far kinder to the knees than stepping forward.',
      '',
      'Photos show the forward/walking version — the bottom position is the same.',
    ].join('\n') },
  { name: 'Calf Raises', type: 'strength', muscles: ['calves'], equipment: 'bodyweight', unit: 'reps', motion_sensitivity: 'high',
    image: IMG('Calf_Raise_On_A_Dumbbell'),
    note: [
      '1. Stand with the balls of your feet on a step, heels hanging free.',
      '2. Rise as high onto your toes as you can.',
      '3. Lower slowly until you feel the stretch at the bottom.',
      '',
      '**Cue:** Achilles and calf insurance for box jumps — ramp these BEFORE you ramp jump volume.',
    ].join('\n') },
  { name: 'Side Plank', type: 'skill', muscles: ['core'], equipment: 'bodyweight', unit: 'seconds',
    note: [
      '1. Lie on your side, elbow directly under the shoulder, feet stacked.',
      '2. Lift the hips so head, hips and heels make one straight line.',
      '3. Hold, then swap sides — time each side separately.',
      '',
      '**Cue:** the lateral half of the plank; your plank note already says to sub these in. Good for the hips and the ITB.',
    ].join('\n') },
  { name: 'Hanging Knee Raise', type: 'skill', muscles: ['core', 'forearms'], equipment: 'bar', unit: 'reps', motion_sensitivity: 'low',
    note: [
      '1. Hang from the bar, shoulders engaged, body still.',
      '2. Raise both knees toward your chest without swinging.',
      '3. Lower slowly all the way down.',
      '',
      '**Cue:** rung one of the toes-to-bar ladder. Own this cleanly before you straighten the legs.',
    ].join('\n') },
  { name: 'Farmer\'s Carry', type: 'strength', muscles: ['forearms', 'core', 'shoulders'], equipment: 'dumbbells', unit: 'kg',
    image: IMG('Farmers_Walk'),
    note: [
      '1. Pick up a heavy dumbbell in each hand.',
      '2. Stand tall — shoulders back and down, ribs stacked over hips.',
      '3. Walk a set distance or time without letting the shoulders round forward.',
      '',
      '**Cue:** grip strength that feeds straight back into dead hangs, pull-ups and eventually the false grip.',
    ].join('\n') },
  { name: 'Band Face Pulls', type: 'mobility', muscles: ['shoulders', 'back'], equipment: 'band', unit: 'reps', motion_sensitivity: 'high',
    image: IMG('Face_Pull'),
    note: [
      '1. Anchor a band at about face height.',
      '2. Pull toward your face with high elbows, hands finishing beside your ears.',
      '3. Squeeze the rear delts for a beat, then return under control.',
      '',
      '**Cue:** with this much pressing, the rear-delt and rotator work is what keeps the shoulders healthy.',
      '',
      'Photos show the cable version — a band does the same job.',
    ].join('\n') },

  /* ---- Running (added 28 Aug 2026): rebuilding toward a comfortable 15km
     on trail after a couple of weeks off sick. Tracked in km — the log
     screen swaps to distance + minutes for these. ---- */
  { name: 'Easy Run', type: 'cardio', muscles: ['quads', 'hamstrings', 'calves', 'glutes'], equipment: 'treadmill or road', unit: 'km',
    note: [
      '1. Start with 3–5 minutes of walking or very slow jogging.',
      '2. Settle into a pace you could hold a conversation at — nose-breathing easy, not "steady".',
      '3. Finish feeling like you could have done another 10 minutes.',
      '',
      '**Cue:** this is the bread and butter — roughly 80% of your running should feel this easy. The gym 30-minute midweek runs are these.',
      '',
      'If you have been ill, easy means EASIER than usual for the first week or two back.',
    ].join('\n') },
  { name: 'Long Trail Run', type: 'cardio', muscles: ['quads', 'hamstrings', 'calves', 'glutes', 'core'], equipment: 'trail', unit: 'km',
    note: [
      '1. Go slower than your road pace from the first step — trail costs more for the same effort.',
      '2. Walk the steep climbs deliberately. Walking uphill is trail running, not failure.',
      '3. Shorten your stride and look 2–3 metres ahead on technical descents.',
      '4. Take water past about 8km, and something to eat past about 90 minutes.',
      '',
      '**Cue:** the weekend run is where the 15km gets built. Time on feet beats pace — never race the ladder.',
    ].join('\n') },
  { name: 'Walk-Run Intervals', type: 'cardio', muscles: ['quads', 'calves', 'glutes'], equipment: 'trail or road', unit: 'km',
    note: [
      '1. Run 4 minutes easy, walk 1 minute. Repeat.',
      '2. Keep the run portions genuinely easy — the walk is a reset, not a rescue.',
      '3. As it gets easier, stretch the run block (5:1, 8:1, 9:1) before dropping the walk entirely.',
      '',
      '**Cue:** the honest way back after illness or a layoff, and the way to make a long run longer before your legs are ready for it continuously. There is no shame in it — plenty of trail runners use it at distance.',
    ].join('\n') },
  { name: 'Hill Repeats', type: 'cardio', muscles: ['quads', 'glutes', 'calves'], equipment: 'trail or road', unit: 'km',
    note: [
      '1. Warm up 10 minutes easy.',
      '2. Run hard-but-controlled up a 45–90 second hill; jog or walk all the way down to recover.',
      '3. Start with 4 repeats, build toward 8. Cool down 10 minutes easy.',
      '',
      '**Cue:** trail-specific strength — this is what makes mountain climbs stop hurting. Add these only once you have 3–4 weeks of easy running back in the legs.',
    ].join('\n') },
  { name: 'Strides', type: 'cardio', muscles: ['quads', 'hamstrings', 'calves'], equipment: 'road or track', unit: 'reps',
    note: [
      '1. After an easy run, accelerate smoothly for about 20 seconds to near-sprint — but relaxed.',
      '2. Ease off and walk until fully recovered (about a minute).',
      '3. 4–6 of them. Never a hard effort; the point is turnover, not fatigue.',
      '',
      '**Cue:** cheap running economy. Keeps the legs fast while all the other running is deliberately slow.',
    ].join('\n') },

  /* ---- Added 28 Aug 2026 for the actual home kit: pull-up bar, dumbbells,
     6kg + 8kg kettlebells, box, bands. The bells are LIGHT for an 87kg
     lifter, so they earn their keep on get-ups, halos and windmills rather
     than as the loading tool — that job belongs to the dumbbells. ---- */
  { name: 'Dumbbell Floor Press', type: 'strength', muscles: ['chest', 'triceps', 'shoulders'], equipment: 'dumbbells', unit: 'kg',
    image: IMG('Dumbbell_Floor_Press'),
    note: [
      '1. Lie on the floor, dumbbells at chest height, knees bent.',
      '2. Press straight up until the arms lock out.',
      '3. Lower until the backs of your upper arms touch the floor, pause, press again.',
      '',
      '**Cue:** the bench press you can do without a bench. The floor caps the range, which is easier on a cranky shoulder than a full-depth press.',
    ].join('\n') },
  { name: 'Standing Dumbbell Press', type: 'strength', muscles: ['shoulders', 'triceps', 'core'], equipment: 'dumbbells', unit: 'kg',
    image: IMG('Standing_Dumbbell_Press'),
    note: [
      '1. Stand tall, dumbbells at shoulder height, palms forward.',
      '2. Brace the ribs down — no leaning back — and press overhead to a full lockout.',
      '3. Lower under control to the shoulders.',
      '',
      '**Cue:** loadable overhead pressing to complement pike and handstand work. Feeds the muscle-up top-out.',
    ].join('\n') },
  { name: 'One-arm Dumbbell Row', type: 'strength', muscles: ['back', 'biceps', 'forearms'], equipment: 'dumbbells', unit: 'kg',
    image: IMG('One-Arm_Dumbbell_Row'),
    note: [
      '1. Hinge forward with one hand braced on the box, back flat.',
      '2. Row the dumbbell to your hip, elbow close, shoulder blade pulling first.',
      '3. Lower all the way to a full stretch.',
      '',
      '**Cue:** the loadable row. Inverted rows are limited by bodyweight — this one keeps getting heavier, which is what a growing back needs.',
    ].join('\n') },
  { name: 'Dumbbell Curl', type: 'strength', muscles: ['biceps'], equipment: 'dumbbells', unit: 'kg', motion_sensitivity: 'high',
    image: IMG('Dumbbell_Bicep_Curl'),
    note: [
      '1. Stand tall, arms at your sides, palms forward.',
      '2. Curl without swinging the elbows forward or rocking the torso.',
      '3. Lower slowly — the lowering is where the growth is.',
      '',
      '**Cue:** direct arm work supports pulling volume; a stronger biceps makes chin-ups and the muscle-up transition easier.',
    ].join('\n') },
  { name: 'Hammer Curls', type: 'strength', muscles: ['biceps', 'forearms'], equipment: 'dumbbells', unit: 'kg', motion_sensitivity: 'high',
    image: IMG('Hammer_Curls'),
    note: [
      '1. Same as a curl, but palms face each other the whole way (thumbs up).',
      '2. Keep the elbows pinned to your sides.',
      '3. Lower under control.',
      '',
      '**Cue:** hits the brachialis and forearm — grip carryover to dead hangs and the false grip.',
    ].join('\n') },
  { name: 'Overhead Triceps Extension', type: 'strength', muscles: ['triceps'], equipment: 'dumbbells', unit: 'kg', motion_sensitivity: 'high',
    image: IMG('Seated_Triceps_Press'),
    note: [
      '1. Hold one dumbbell overhead in both hands.',
      '2. Lower it behind your head by bending only at the elbows.',
      '3. Press back to lockout, elbows staying close to your ears.',
      '',
      '**Cue:** the lockout strength that finishes a dip and a muscle-up.',
    ].join('\n') },
  { name: 'Lateral Raise', type: 'strength', muscles: ['shoulders'], equipment: 'dumbbells', unit: 'kg', motion_sensitivity: 'high',
    image: IMG('Side_Lateral_Raise'),
    note: [
      '1. Stand tall, light dumbbells at your sides, a soft bend in the elbows.',
      '2. Raise out to the sides to shoulder height — no higher, no swinging.',
      '3. Lower slowly.',
      '',
      '**Cue:** go lighter than feels right. This one is about the side delt, not the weight — the 6kg bell or a light dumbbell is plenty.',
    ].join('\n') },
  { name: 'Reverse Flyes', type: 'strength', muscles: ['shoulders', 'back'], equipment: 'dumbbells', unit: 'kg', motion_sensitivity: 'high',
    image: IMG('Reverse_Flyes'),
    note: [
      '1. Hinge forward, back flat, light dumbbells hanging straight down.',
      '2. Raise them out to the sides, squeezing the shoulder blades together.',
      '3. Lower under control.',
      '',
      '**Cue:** rear delts — the other half of the shoulder-health work alongside rows and face pulls. Light weight, strict form.',
    ].join('\n') },
  { name: 'Renegade Row', type: 'strength', muscles: ['back', 'core', 'shoulders'], equipment: 'dumbbells', unit: 'kg',
    image: IMG('Alternating_Renegade_Row'),
    note: [
      '1. Top of a push-up with a hand on each dumbbell, feet wide for balance.',
      '2. Row one dumbbell to your hip WITHOUT letting the hips rotate.',
      '3. Replace it, then row the other side.',
      '',
      '**Cue:** anti-rotation core plus a row in one. The hips staying square is the exercise; if they twist, go lighter.',
      '',
      'Photos show the kettlebell version — dumbbells are identical, and a little more stable.',
    ].join('\n') },
  { name: 'Kettlebell Thruster', type: 'strength', muscles: ['full body', 'shoulders', 'quads'], equipment: 'kettlebell', unit: 'kg',
    image: IMG('Kettlebell_Thruster'),
    note: [
      '1. Hold the bell(s) at your shoulders and squat to depth.',
      '2. Drive up and let that momentum carry into an overhead press in one motion.',
      '3. Return to the shoulders and go straight into the next rep.',
      '',
      '**Cue:** the whole body in one movement — a brutal conditioning finisher where a light 8kg bell is genuinely enough for high reps.',
    ].join('\n') },
  { name: 'Turkish Get-Up', type: 'skill', muscles: ['full body', 'core', 'shoulders'], equipment: 'kettlebell', unit: 'kg',
    image: IMG('Kettlebell_Turkish_Get-Up_Squat_style'),
    note: [
      '1. Lie on your back, one arm holding the bell straight up. Never take your eyes off it.',
      '2. Roll to your elbow, then your hand, bridge the hips up, sweep the trailing leg back to a lunge.',
      '3. Stand up. Then reverse every step, slowly, to get back down.',
      '',
      '**Cue:** the single best use of a light kettlebell you own — shoulder stability, core control and hip mobility in one 30-second rep. Do them slowly. 6kg is plenty to start.',
    ].join('\n') },
  { name: 'Kettlebell Windmill', type: 'mobility', muscles: ['core', 'shoulders', 'hamstrings'], equipment: 'kettlebell', unit: 'kg',
    image: IMG('Kettlebell_Windmill'),
    note: [
      '1. Bell locked out overhead, feet turned out about 45 degrees away from it.',
      '2. Push the hip under the bell out to the side and hinge down, sliding your free hand down the inside of your leg.',
      '3. Keep your eyes on the bell the whole time; stand back up under control.',
      '',
      '**Cue:** thoracic and hamstring mobility under load. Light bell, no rushing — this is the one that keeps a long spine moving well.',
    ].join('\n') },
  { name: 'Kettlebell Halo', type: 'mobility', muscles: ['shoulders', 'core'], equipment: 'kettlebell', unit: 'reps', motion_sensitivity: 'high',
    note: [
      '1. Hold the bell upside down by the horns at chest height.',
      '2. Circle it slowly around your head, close to it, keeping the ribs down.',
      '3. Same number of circles each direction.',
      '',
      '**Cue:** shoulder warm-up gold and a perfect job for the 6kg bell. Do these before pressing days.',
    ].join('\n') },
  { name: 'Negative Pull-ups', type: 'strength', muscles: ['back', 'biceps'], equipment: 'bar', unit: 'reps',
    note: [
      '1. Jump or step up so your chin starts above the bar.',
      '2. Lower yourself as SLOWLY as you can — aim for 5 seconds, work toward 8–10.',
      '3. Step back up; do not try to pull yourself up.',
      '',
      '**Cue:** the highest-value pull-up builder there is. When reps stall, negatives are what break the plateau — you are strong on the lowering long before the lifting.',
    ].join('\n') },
  { name: 'Archer Pull-ups', type: 'skill', muscles: ['back', 'biceps', 'core'], equipment: 'bar', unit: 'reps',
    note: [
      '1. Take a wide grip. Pull up toward one hand while the other arm stays nearly straight, guiding.',
      '2. Alternate sides each rep.',
      '',
      '**Cue:** the bridge from two-arm pull-ups toward one-arm strength, and serious extra load without extra weight. Only once 8–10 clean pull-ups are yours.',
    ].join('\n') },
  { name: 'Tuck Front Lever', type: 'skill', muscles: ['back', 'core'], equipment: 'bar', unit: 'seconds',
    note: [
      '1. Hang from the bar, then pull the shoulder blades down and back.',
      '2. Tuck the knees to your chest and lift the hips until your back is horizontal.',
      '3. Hold. Straighten the legs a little more as it gets easier.',
      '',
      '**Cue:** teaches the straight-arm pulling strength and hollow body that make the muscle-up transition feel less like a fight.',
    ].join('\n') },
  { name: 'Bodyweight Squat', type: 'strength', muscles: ['quads', 'glutes'], equipment: 'bodyweight', unit: 'reps',
    image: IMG('Bodyweight_Squat'),
    note: [
      '1. Feet shoulder width, toes slightly out.',
      '2. Sit down and back, knees tracking over the toes, chest up.',
      '3. Go as deep as you can hold a flat back, then drive up through mid-foot.',
      '',
      '**Cue:** the movement everything else is built on, and a fine warm-up or high-rep finisher on its own.',
    ].join('\n') },
  { name: 'Close-grip Push-ups', type: 'strength', muscles: ['triceps', 'chest'], equipment: 'bodyweight', unit: 'reps',
    image: IMG('Close-Grip_Push-Up_off_of_a_Dumbbell'),
    note: [
      '1. Hands directly under the chest, close together (on dumbbells if your wrists prefer it).',
      '2. Lower with the elbows tracking BACK along your ribs, not flaring out.',
      '3. Press to a full lockout.',
      '',
      '**Cue:** triceps-dominant pressing that carries straight into dips and the muscle-up lockout.',
    ].join('\n') },
  { name: 'Burpees', type: 'cardio', muscles: ['full body'], equipment: 'bodyweight', unit: 'reps',
    note: [
      '1. Squat down, hands to the floor, jump the feet back to a plank.',
      '2. Chest to the floor (or a push-up), then jump the feet back in.',
      '3. Stand and jump with the hands overhead.',
      '',
      '**Cue:** conditioning with no equipment and nowhere to hide. Sets of 10 at an easy pace beat one all-out set — and go easy on these while you are rebuilding after illness.',
    ].join('\n') },
  { name: 'Wall Sit', type: 'skill', muscles: ['quads'], equipment: 'bodyweight', unit: 'seconds',
    note: [
      '1. Back flat against a wall, slide down until your knees are at 90 degrees.',
      '2. Thighs parallel to the floor, weight in the heels.',
      '3. Hold and breathe.',
      '',
      '**Cue:** quad endurance for long trail descents, with none of the impact. A useful one on days the knees do not want jumping.',
    ].join('\n') },

  /* ---- Recovery (added 28 Aug 2026). Aimed at the watch-outs a profile
     typically records, plus what running tightens.
     These are what a rest day is FOR; they are not a workout. ---- */
  { name: 'IT Band and Glute Stretch', type: 'mobility', muscles: ['glutes', 'quads'], equipment: 'bodyweight', unit: 'seconds',
    image: IMG('IT_Band_and_Glute_Stretch'),
    note: [
      '1. Sit with one leg crossed over the other, that foot flat on the floor.',
      '2. Hug the raised knee across your body and rotate gently toward it.',
      '3. Breathe out into the stretch. 30–60 seconds a side.',
      '',
      '**Cue:** the direct answer to a grumbling ITB. Do this one on rest days and after every long trail run — the band itself does not stretch, but the glute and TFL feeding it do.',
    ].join('\n') },
  { name: "World's Greatest Stretch", type: 'mobility', muscles: ['full body', 'quads', 'core'], equipment: 'bodyweight', unit: 'reps',
    image: IMG('Worlds_Greatest_Stretch'),
    note: [
      '1. Step into a deep lunge, both hands inside the front foot.',
      '2. Drop the back knee slightly, then rotate the inside arm up to the ceiling and follow it with your eyes.',
      '3. Return, swap sides. 5 each side.',
      '',
      '**Cue:** earns its name — hips, thoracic spine, hamstrings and ankles in one movement. The single best thing to do before a run or on a rest day.',
    ].join('\n') },
  { name: 'Kneeling Hip Flexor Stretch', type: 'mobility', muscles: ['quads', 'core'], equipment: 'bodyweight', unit: 'seconds',
    image: IMG('Kneeling_Hip_Flexor'),
    note: [
      '1. Half-kneel, back knee down, front foot flat.',
      '2. Tuck the tailbone under (this is the bit people skip) and shift gently forward.',
      '3. You should feel it at the front of the back hip, not the lower back. 30–45 seconds a side.',
      '',
      '**Cue:** running and desk-sitting both shorten these, and tight hip flexors are a common driver of lower-back complaints.',
    ].join('\n') },
  { name: 'Cat-Cow', type: 'mobility', muscles: ['back', 'core'], equipment: 'bodyweight', unit: 'reps',
    image: IMG('Cat_Stretch'),
    note: [
      '1. On hands and knees, slowly round the spine toward the ceiling.',
      '2. Then reverse: let the belly drop and the chest open.',
      '3. Move with your breath, 8–10 slow cycles.',
      '',
      '**Cue:** gentle spinal movement with no load — a good first thing on any morning the lower back feels stiff.',
    ].join('\n') },
  { name: "Child's Pose", type: 'mobility', muscles: ['back', 'shoulders'], equipment: 'bodyweight', unit: 'seconds',
    image: IMG('Childs_Pose'),
    note: [
      '1. Kneel, sit back onto your heels and reach the arms long in front.',
      '2. Let the chest sink toward the floor and breathe into the back of the ribs.',
      '3. Hold 60 seconds or more.',
      '',
      '**Cue:** decompresses the lower back and opens the shoulders. Costs nothing and is a fine way to end any session.',
    ].join('\n') },
  { name: 'Calf Stretch', type: 'mobility', muscles: ['calves'], equipment: 'bodyweight', unit: 'seconds',
    image: IMG('Calf_Stretch_Hands_Against_Wall'),
    note: [
      '1. Hands on a wall, one leg back, heel down, that leg straight.',
      '2. Lean in until you feel the upper calf. 30 seconds.',
      '3. Then bend the back knee slightly to shift it to the lower calf and Achilles. 30 seconds more.',
      '',
      '**Cue:** both positions matter — the straight-leg version hits the gastroc, the bent-knee one the soleus and Achilles. Non-negotiable once box jumps and hills are in the mix.',
    ].join('\n') },
  { name: 'Hamstring Stretch', type: 'mobility', muscles: ['hamstrings'], equipment: 'bodyweight', unit: 'seconds',
    image: IMG('Hamstring_Stretch'),
    note: [
      '1. Sit or lie with one leg straight, the other bent out of the way.',
      '2. Hinge from the HIP with a flat back — a rounded spine stretches the back, not the hamstring.',
      '3. 30–60 seconds a side.',
      '',
      '**Cue:** flat back is the whole instruction. Especially so with a lower-back history.',
    ].join('\n') },
  { name: 'Piriformis Stretch', type: 'mobility', muscles: ['glutes'], equipment: 'bodyweight', unit: 'seconds',
    image: IMG('Piriformis-SMR'),
    note: [
      '1. Lie on your back, ankle crossed over the opposite knee in a figure four.',
      '2. Pull the underneath thigh toward your chest.',
      '3. 30–60 seconds a side.',
      '',
      '**Cue:** deep glute. A tight piriformis refers pain into the back and down the leg, so this is worth the two minutes.',
    ].join('\n') },
  { name: 'Spinal Twist', type: 'mobility', muscles: ['back', 'core'], equipment: 'bodyweight', unit: 'seconds',
    image: IMG('Spinal_Stretch'),
    note: [
      '1. Lie on your back, arms out wide, knees bent.',
      '2. Let both knees fall slowly to one side while the opposite shoulder stays down.',
      '3. Breathe, 30–60 seconds, then the other side.',
      '',
      '**Cue:** gentle rotation for a back that spends the week hanging, pressing and running in one plane.',
    ].join('\n') },
  { name: 'Shoulder Circles', type: 'mobility', muscles: ['shoulders'], equipment: 'bodyweight', unit: 'reps', motion_sensitivity: 'high',
    image: IMG('Round_The_World_Shoulder_Stretch'),
    note: [
      '1. Arms out to the sides, draw slow full circles — small building to large.',
      '2. 10 forward, 10 back, unhurried.',
      '',
      '**Cue:** keeps the shoulder moving through its whole range on the days you are not loading it. Gentle and controlled beats aggressive every time, especially if you have any shoulder or nerve history.',
    ].join('\n') },
  { name: 'Recovery Walk', type: 'cardio', muscles: ['full body'], equipment: 'outdoors', unit: 'km',
    image: IMG('Trail_Running_Walking'),
    note: [
      '1. 20–40 minutes at an easy, conversational walking pace.',
      '2. Outside if you can — flat ground, nothing technical.',
      '',
      '**Cue:** the most underrated recovery tool there is. Moves blood through tired legs without adding training stress, and it still counts as a good day.',
    ].join('\n') },
];

const SEED_PLAN = {
  name: 'Get Over The Bar',
  fm: { active: true },
  body: [
    'At-home strength, four days a week, ~30 minutes a session. One hard goal — the',
    'muscle-up — with rows for shoulder health, a full leg & core day, and mobility',
    'built into every warm-up.',
    '',
    'THE WEEK: Mon pull, Wed push, Thu legs & core — with the running plan',
    'filling Tue and Sat, and the Rest & Recovery plan filling whatever is',
    'left. Five sessions and two rest days.',
    'Legs sit on Thursday so there is a clear day between them and the',
    'Saturday trail run; a leg session the day before a long run is how ITBs',
    'and knees get angry. Adding running cost the second pull day (the old',
    'Sat A*) — recovery is the ceiling at 40, and the fix for a stalled',
    'muscle-up is less volume, not more days.',
    '',
    'Warm-up before every session (~5 min, non-negotiable): shoulder rolls + big arm',
    'circles, 2×5 scapular pull-ups, a mobility minute (thoracic rotations, deep',
    'squat holds, wrist circles), 15 band pull-aparts, 10 easy box step-ups, 20s',
    'hollow hold. On jump days add 5 easy non-max jumps.',
    '',
    '## A · Pull Priority (mon)',
    '',
    'Strength for the muscle-up. Rest ~90s between hard sets; stop 1–2 reps before failure.',
    '',
    '- Pull-ups | 5 x submax',
    '- Explosive High Pull-ups | 4 x 3',
    '- Inverted Rows | 3 x 8-12',
    '- Straight-bar Dips | 3 x 5-8',
    '- Box Jumps | 4 x 8-10',
    '- Dead Hang | 2 x 30-45s',
    '',
    '## B · Push + Volume (wed)',
    '',
    'The other half of the muscle-up — dips lead today. Clean reps, leave 2 in the tank.',
    '',
    '- Straight-bar Dips | 5 x submax',
    '- Pull-ups | 4 x submax',
    '- Push-ups | 3 x 10-15',
    '- Inverted Rows | 3 x 8-12',
    '- Plank | 3 x 65% max',
    '',
    '## C · Legs, Hinge & Core (thu)',
    '',
    'Strength + skill, on its own track. Superset a leg move with a core move to stay inside 30 minutes.',
    '',
    '- Romanian Deadlift | 3 x 8-10',
    '- Bulgarian Split Squat | 3 x 8/leg',
    '- Pistol Squat Progression | 3 x 3-5/leg',
    '- Toes-to-bar Ladder | 4 x 6-10',
    '- L-sit & Dragon Flag | 3 x holds',
    '',
  ].join('\n') + '\n',
};

/* Running lives in its OWN plan, marked `parallel` — it is not an
   alternative to the strength plan, it runs alongside it, so the dashboard
   merges days from the active plan and every parallel one. The ladder is
   frontmatter data (not prose) so the Running page can say which week you
   are in and what today's target is. */
const SEED_RUN_PLAN = {
  name: 'Trail Base — Road to 15km',
  fm: {
    parallel: true,
    ladder: [4, 5, 6, 5, 7, 8, 9, 6, 10, 11.5, 13, 15],
    start_date: '',          // set on setup to the Monday of the current week
  },
  body: [
    'Rebuilding to a comfortable 15km on trail. An easy 30-minute run on',
    'Tuesday and the long trail run on Saturday. Want a second easy run?',
    'Friday is the place for it — never the day after legs.',
    '',
    'The long-run ladder steps DOWN in weeks 4 and 8 on purpose — that is',
    'where the adaptation lands. Coming back from illness, walk-run the first',
    'week or two rather than forcing it, and repeat a week whenever it felt',
    'hard. The ladder is a guide, not a contract.',
    '',
    '## Easy Run (tue)',
    '',
    '30 minutes conversational. Treadmill or road — whatever gets it done.',
    '',
    '- Easy Run | 1 x 30 min easy',
    '',
    '## Long Trail Run (sat)',
    '',
    'Mountain or forest. Slow, and walk the climbs.',
    '',
    '- Long Trail Run | 1 x per the ladder',
  ].join('\n') + '\n',
};

/* Rest & Recovery is a FALLBACK plan: it does not compete with the training
   plan, it fills whatever weekday nothing else claims. Rest therefore never
   has to be re-arranged by hand when training days move or the active plan
   changes. `(any)` is the wildcard day; an exact weekday wins over it. */
const SEED_REST_PLAN = {
  name: 'Rest & Recovery',
  fm: { parallel: true, fallback: true },
  body: [
    'Not a programme you switch to — this fills any day your training plan',
    'leaves empty, whichever plan that is. Nothing here is compulsory: pick',
    'what feels tight. Sleep and food are the actual training on these days.',
    '',
    '## Rest & Recovery (any)',
    '',
    'The default recovery day.',
    '',
    "- World's Greatest Stretch | 1 x 5/side",
    '- Kneeling Hip Flexor Stretch | 1 x 45s/side',
    '- IT Band and Glute Stretch | 1 x 45s/side',
    '- Cat-Cow | 1 x 8-10 slow',
    '- Recovery Walk | 1 x 20-30 min easy',
    '',
    '## Rest & Recovery · after the long run (sun)',
    '',
    'The trail tightens different things than the gym does.',
    '',
    '- IT Band and Glute Stretch | 1 x 45s/side',
    '- Piriformis Stretch | 1 x 45s/side',
    '- Calf Stretch | 1 x 30s each position',
    "- Child's Pose | 1 x 60s",
    '- Recovery Walk | 1 x 20-30 min easy',
  ].join('\n') + '\n',
};

const SEED_GOALS = [
  { name: '10 Pull-ups', fm: { metric: 'exercise-reps', exercise: 'Pull-ups', target: 10, direction: 'increase' },
    note: 'The first gateway — muscle-up skill work unlocks at 8–10 clean pull-ups (with the dip gateway).' },
  { name: '10 Straight-bar Dips', fm: { metric: 'exercise-reps', exercise: 'Straight-bar Dips', target: 10, direction: 'increase' },
    note: 'The other gateway. Hit both and Phase 2 (muscle-up skill work) opens.' },
  { name: '10 Muscle-ups', fm: { metric: 'exercise-reps', exercise: 'Muscle-ups', target: 10, direction: 'increase' },
    note: 'The mission. A year-plus goal — patience is the plan. First rep → ten reps, consistency beats intensity.' },
  { name: '50 Box Jumps', fm: { metric: 'exercise-reps', exercise: 'Box Jumps', target: 50, direction: 'increase' },
    note: 'Add 2–4 reps a week. Landings over height, always; step down every rep.' },
  { name: '6-minute Plank', fm: { metric: 'exercise-duration', exercise: 'Plank', target: 360, direction: 'increase' },
    note: 'Add 10–15s a week, test max monthly.' },
  { name: '5 Pistol Squats per Leg', fm: { metric: 'exercise-reps', exercise: 'Pistol Squat Progression', target: 5, direction: 'increase' },
    note: 'Shrink the assistance: lower box → no box. Gated mostly by ankle/hip mobility.' },
  { name: '45s Dead Hang', fm: { metric: 'exercise-duration', exercise: 'Dead Hang', target: 45, direction: 'increase' },
    note: 'Grip + shoulder prehab.' },
  { name: '10km Trail Run', fm: { metric: 'exercise-distance', exercise: 'Long Trail Run', target: 10, direction: 'increase' },
    note: 'The halfway marker on the way to 15. Around week 9 of the ladder.' },
  { name: '15km Trail Run', fm: { metric: 'exercise-distance', exercise: 'Long Trail Run', target: 15, direction: 'increase' },
    note: 'The mission: 15km on trail, comfortably. No deadline on purpose — coming back from illness, the body sets the pace. Add one later if you want the pressure.' },
  { name: '4 Workouts a Week', fm: { metric: 'workouts-per-week', target: 4, direction: 'increase' },
    note: 'A, B, C and the Saturday repeat. Recovery is the real ceiling — if progress stalls, cut volume, don\'t add days.' },
];

const SEED_PROFILE = {
  fm: { name: '', birth_year: '', height_cm: '', sex: '' },
  /* Starter prompts, not someone else's history: this note ships to every
     new vault, so it asks the questions rather than answering them with the
     author's own injuries and age. */
  body: [
    'Training context: note anything that shapes how you train — age, build,',
    'how long you have been training, time available in a week.',
    '',
    'Watch-outs: list your own injury history and anything a session should',
    'work around. Sharp joint pain (shoulder, elbow, wrist, knee) means stop',
    'that exercise. Muscle burn is fine; joint pain is a warning. Sleep and',
    'food are half the program.',
  ].join('\n') + '\n',
};

module.exports = { SEED_EXERCISES, SEED_PLAN, SEED_RUN_PLAN, SEED_REST_PLAN, SEED_GOALS, SEED_PROFILE, isSeedMediaUrl };
