'use strict';
/* First-run starter files. Pure data — no DOM, no obsidian import.

   Seeded from Ruan's real "Get Over The Bar" program (at-home strength,
   4 days/week, one hard goal — the muscle-up) rather than a generic library,
   so the plugin is useful the moment it's set up. Every file here is written
   with writeIfAbsent: a re-run never overwrites real data. */

const SEED_EXERCISES = [
  { name: 'Pull-ups', type: 'strength', muscles: ['back', 'biceps', 'forearms'], equipment: 'bar', unit: 'reps',
    note: 'Stop 1–2 reps before failure every set — quality volume, not grinding. Half of the muscle-up.' },
  { name: 'Explosive High Pull-ups', type: 'strength', muscles: ['back', 'biceps'], equipment: 'bar', unit: 'reps',
    note: 'Pull as high as you can — chest, then belly toward the bar. Trains the "pop".' },
  { name: 'Inverted Rows', type: 'strength', muscles: ['back', 'shoulders'], equipment: 'bar', unit: 'reps',
    note: 'Body straight as a plank, pull chest to the bar. Shoulder-health insurance — keep rows in even when time is tight.' },
  { name: 'Straight-bar Dips', type: 'strength', muscles: ['chest', 'triceps', 'shoulders'], equipment: 'bar', unit: 'reps',
    note: 'Full lockout at the top. The other half of the muscle-up.' },
  { name: 'Push-ups', type: 'strength', muscles: ['chest', 'triceps', 'core'], equipment: 'bodyweight', unit: 'reps',
    note: 'Elevate hands on the box if full push-ups are tough.' },
  { name: 'Box Jumps', type: 'strength', muscles: ['quads', 'glutes', 'calves'], equipment: 'box', unit: 'reps',
    note: 'Soft, quiet landing. Step down every rep — never jump down. Landings over height, always.' },
  { name: 'Dead Hang', type: 'skill', muscles: ['forearms', 'shoulders'], equipment: 'bar', unit: 'seconds',
    note: 'Just hang. Grip + shoulder decompression — prehab gold at 40.' },
  { name: 'Plank', type: 'skill', muscles: ['core'], equipment: 'bodyweight', unit: 'seconds',
    note: 'Flat back, hips don\'t sag. Sub in side planks now and then.' },
  { name: 'Romanian Deadlift', type: 'strength', muscles: ['hamstrings', 'glutes', 'back'], equipment: 'dumbbells', unit: 'kg',
    note: 'Hips back, soft knees, load the hamstrings — chest stays proud. Two-leg first, progress to single-leg.' },
  { name: 'Bulgarian Split Squat', type: 'strength', muscles: ['quads', 'glutes'], equipment: 'dumbbells', unit: 'kg',
    note: 'Rear foot up on the box. Add weight when 8 feels easy. Leads to the pistol.' },
  { name: 'Pistol Squat Progression', type: 'skill', muscles: ['quads', 'glutes', 'core'], equipment: 'bodyweight', unit: 'reps',
    note: 'Box-assisted (sit to box) → higher surface → full. Superset with split squats early on.' },
  { name: 'Toes-to-bar Ladder', type: 'skill', muscles: ['core', 'forearms'], equipment: 'bar', unit: 'reps',
    note: 'Work the first rung you can\'t cheat: knee raise → leg raise → toes-to-bar. Slow, no swinging.' },
  { name: 'L-sit / Dragon Flag', type: 'skill', muscles: ['core'], equipment: 'bodyweight', unit: 'seconds',
    note: 'Add only once toes-to-bar is solid. L-sit off the floor or two dumbbells; dragon flag anchored to a bench.' },
  { name: 'Muscle-ups', type: 'skill', muscles: ['back', 'chest', 'triceps', 'core'], equipment: 'bar', unit: 'reps',
    note: 'The mission. Unlocks as skill work at 8–10 clean pull-ups AND 8–10 clean dips (band-assisted reps + negatives first).' },
];

const SEED_PLAN = {
  name: 'Get Over The Bar',
  fm: { active: true },
  body: [
    'At-home strength, four days a week, ~30 minutes a session. One hard goal — the',
    'muscle-up — with rows for shoulder health, a full leg & core day, and mobility',
    'built into every warm-up.',
    '',
    'Warm-up before every session (~5 min, non-negotiable): shoulder rolls + big arm',
    'circles, 2×5 scapular pull-ups, a mobility minute (thoracic rotations, deep',
    'squat holds, wrist circles), 15 band pull-aparts, 10 easy box step-ups, 20s',
    'hollow hold. On jump days add 5 easy non-max jumps.',
    '',
    '## A · Pull Priority (mon)',
    '',
    'Strength for the muscle-up. Rest ~90s between hard sets; stop 1–2 reps before failure.',
    '',
    '- Pull-ups | 5 x submax',
    '- Explosive High Pull-ups | 4 x 3',
    '- Inverted Rows | 3 x 8-12',
    '- Straight-bar Dips | 3 x 5-8',
    '- Box Jumps | 4 x 8-10',
    '- Dead Hang | 2 x 30-45s',
    '',
    '## B · Push + Volume (wed)',
    '',
    'The other half of the muscle-up — dips lead today. Clean reps, leave 2 in the tank.',
    '',
    '- Straight-bar Dips | 5 x submax',
    '- Pull-ups | 4 x submax',
    '- Push-ups | 3 x 10-15',
    '- Inverted Rows | 3 x 8-12',
    '- Plank | 3 x 65% max',
    '',
    '## C · Legs, Hinge & Core (fri)',
    '',
    'Strength + skill, on its own track. Superset a leg move with a core move to stay inside 30 minutes.',
    '',
    '- Romanian Deadlift | 3 x 8-10',
    '- Bulgarian Split Squat | 3 x 8/leg',
    '- Pistol Squat Progression | 3 x 3-5/leg',
    '- Toes-to-bar Ladder | 4 x 6-10',
    '- L-sit / Dragon Flag | 3 x holds',
    '',
    '## A* · Pull Priority (sat)',
    '',
    'Repeat of Day A, slightly lighter if Monday was hard.',
    '',
    '- Pull-ups | 5 x submax',
    '- Explosive High Pull-ups | 4 x 3',
    '- Inverted Rows | 3 x 8-12',
    '- Straight-bar Dips | 3 x 5-8',
    '- Box Jumps | 4 x 8-10',
    '- Dead Hang | 2 x 30-45s',
  ].join('\n') + '\n',
};

const SEED_GOALS = [
  { name: '10 Pull-ups', fm: { metric: 'exercise-reps', exercise: 'Pull-ups', target: 10, direction: 'increase' },
    note: 'The first gateway — muscle-up skill work unlocks at 8–10 clean pull-ups (with the dip gateway).' },
  { name: '10 Straight-bar Dips', fm: { metric: 'exercise-reps', exercise: 'Straight-bar Dips', target: 10, direction: 'increase' },
    note: 'The other gateway. Hit both and Phase 2 (muscle-up skill work) opens.' },
  { name: '10 Muscle-ups', fm: { metric: 'exercise-reps', exercise: 'Muscle-ups', target: 10, direction: 'increase' },
    note: 'The mission. A year-plus goal — patience is the plan. First rep → ten reps, consistency beats intensity.' },
  { name: '50 Box Jumps', fm: { metric: 'exercise-reps', exercise: 'Box Jumps', target: 50, direction: 'increase' },
    note: 'Add 2–4 reps a week. Landings over height, always; step down every rep.' },
  { name: '6-minute Plank', fm: { metric: 'exercise-duration', exercise: 'Plank', target: 360, direction: 'increase' },
    note: 'Add 10–15s a week, test max monthly.' },
  { name: '5 Pistol Squats per Leg', fm: { metric: 'exercise-reps', exercise: 'Pistol Squat Progression', target: 5, direction: 'increase' },
    note: 'Shrink the assistance: lower box → no box. Gated mostly by ankle/hip mobility.' },
  { name: '45s Dead Hang', fm: { metric: 'exercise-duration', exercise: 'Dead Hang', target: 45, direction: 'increase' },
    note: 'Grip + shoulder prehab.' },
  { name: '4 Workouts a Week', fm: { metric: 'workouts-per-week', target: 4, direction: 'increase' },
    note: 'A, B, C and the Saturday repeat. Recovery is the real ceiling — if progress stalls, cut volume, don\'t add days.' },
];

const SEED_PROFILE = {
  fm: { name: '', birth_year: '', height_cm: '', sex: '' },
  body: [
    'Training context: an athlete's age and build — longer levers mean more range to travel, and',
    'tendons adapt slower than muscle, so explosive work ramps gradually.',
    '',
    'Watch-outs: your own injury history. Sharp joint pain',
    '(shoulder, elbow, wrist, knee) = stop that exercise. Muscle burn is fine;',
    'joint pain is a warning. Sleep and food are half the program.',
  ].join('\n') + '\n',
};

module.exports = { SEED_EXERCISES, SEED_PLAN, SEED_GOALS, SEED_PROFILE };
